### ISSUE TITLE
Request for reading of notification permissions

### ISSUE THREAD

**Issue by Logan-nk** [Unity-Technologies/NotificationsSamples#34]
Reading if notification permissions have been enabled/disabled on device would be immensely helpful when setting up notifications.

**Comment by kenofori** [comment]
+1

**Comment by vaidasma** [comment]
you can use authorization requests for iOS:
https://docs.unity3d.com/Packages/com.unity.mobile.notifications@1.4/api/Unity.Notifications.iOS.AuthorizationRequest.html

For Android (permissions in general, since Android does not have notification permissions) from Unity 2020.x. Check the following documentation on how to query the permission status:

https://docs.unity3d.com/Manual/android-RequestingPermissions.html

If you still have issues after trying to implement these, do contact us again!

**Comment by Logan-nk** [comment]
Android requesting permissions is no longer available for notifications. It looks like checking if notifications are enabled is now on a channel by channel basis, and is a native android functionality. Would like to request again for a wrapper to read these things inside the plugin.
