### ISSUE TITLE
Missing componets problem

### ISSUE THREAD

**Issue by fernandogcat** [Unity-Technologies/NotificationsSamples#54]
Hello,

I've cloned the repo to the latest commit now (https://github.com/Unity-Technologies/NotificationsSamples/commit/e66e6b2fd1e84cdf7d76f65ddaadb75cf8a0c645) and opened in Unity 2018.4.28f1 and there are many GameObjects having its components missing:

![newsfeedbtn-ko](https://user-images.githubusercontent.com/204443/96333626-5b0c2600-106b-11eb-950a-b93e700d23a3.png)

Going a couple commits back (https://github.com/Unity-Technologies/NotificationsSamples/commit/c4c6ff6c6da1adaf231a662f1fbb62748b5b2e80) it looks ok with the same Unity version (even it has to upgrade from 2018.3.0f2 to 2018.4.28f1):

![newsfeedbtn-ok](https://user-images.githubusercontent.com/204443/96333674-a0305800-106b-11eb-97ea-05de68b47f9b.png)

You can appreciate the problem is with the UI components that for some reason can't be reconstructed properly in the latest commits.

Reverting Console.prefab, GameUI,prefab and Demo.unity scene from the working the working commit to the latest one fixes the issue but maybe I'm missing some updates you did in the latest version.

Thanks!

**Comment by vaidasma** [comment]
Hey, we've checked this 2021.1, and the issue is no longer reproducible.

Please try upgrading to a supported Unity release, the oldest one being 2010.4
More about Unity LTS releases here:
https://unity3d.com/unity/qa/lts-releases

If you're still having this issues after upgrading, feel free to contact us again.
