### ISSUE TITLE
IOS Remote notficaion Payload missing

### ISSUE THREAD

**Issue by ZahidZafar** [Unity-Technologies/NotificationsSamples#55]
Hello,
I am unable to get the payload from the remote notification. It tried iOSNotification.Data. But it is empty.

**Comment by IgorGalimski** [comment]
Hi!
It's because Unity parses data from dictionary where a key is 'data'
<img width="1146" alt="Screen Shot 2020-10-21 at 11 50 38" src="https://user-images.githubusercontent.com/19680568/96696640-aa1bc900-1393-11eb-8f13-fc03c26ee521.png">

Because Unity puts when you schedule local push
<img width="1181" alt="Screen Shot 2020-10-21 at 11 53 58" src="https://user-images.githubusercontent.com/19680568/96697035-1eef0300-1394-11eb-86ac-1e4aed9928d5.png">

To have ability to parse data from remote pushes I wrote my own plugin
https://github.com/IgorGalimski/UnityLocalNotification
Please, contact me if you decided to use it

**Comment by aurimasc** [comment]
In upcoming version the user info dictionary is available in the API.
