### ISSUE TITLE
add multi line notification support

### ISSUE THREAD

**Issue by YehudaK** [Unity-Technologies/NotificationsSamples#9]
Currently only few words are shown while the rest of the text is hidden. Do you plan to add:

`.setStyle(new Notification.BigTextStyle().bigText(longText))
`

Thanks

**Comment by mikaelbo** [comment]
Hopefully they can add this in `GameNotificationsManager`. I would make a pr, but I've modified my manager a lot due to some thing not working properly on iOS. 

You can set the style in `AndroidGameNotification.cs`. On line 78, you can add the following below:
`internalNotification.Style = NotificationStyle.BigTextStyle;`

**Comment by YehudaK** [comment]
Thanks @mikaelbo, it worked! I had not clue that I can access style property via AndroidNotification object! All they need to do is to add this information to docs. I personally created my own Notification manager to have better control over notifications in my app.
